#notes:
#sample names cannot contain dash - or period . characters, wildcard constraints occasionally prevent these

#META PIPELINE SETTINGS
pipelines_to_deploy:
  - aref
  # - srna
  # - ldna
  # - lrna

#PIPELINE SETTINGS - Ignore settings for pipelines not being deployed
aref:
  prefix: aref
  sample_table: "conf/sample_table_aref.csv"
  levels:
    - "N2102EP"
  default_palette: "ggsci::default_aaas"
  #MODULE PATHS
  dorado: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/bin/dorado"
  basecallingModel:
    4khz:
      hac: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/models/dna_r10.4.1_e8.2_400bps_hac@v4.1.0"
      sup: "/oscar/data/jsedivy/mkelsey/tools/rerio/dorado_models/res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1"
    5khz:
      hac: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/models/dna_r10.4.1_e8.2_400bps_hac@v4.2.0"

  rate: "5khz"
  type: "hac"
  modification_string: "5mCG_5hmCG"
  #note separete modifications with dashes

  #MODULE LOGIC
  symlink_aref:
    response: "no"
    aref_symlinkdir: "/oscar/data/jsedivy/mkelsey/ref/pipeline_annotations/hs1/RTE/aref"
  symlink_aref_contents:
    response: "no"
  samples: 
    - "N2102EP1"
    
  update_ref_with_tldr:
    response: "no"
    #if making one ref per sample (i.e. each sample has unique inserts), then "yes", else "no"
    per_sample: "no"
    #IF updating reference with tldr inserts; else NULL
    tldr_input_bam_ref: /users/mkelsey/data/ref/pipeline_annotations/hs1/RTE/aref/A.REF.fa
    #ensure tldr_input_bams are a full path, not relative paths
    tldr_te_ref: /oscar/data/jsedivy/mkelsey/tools/tldr/ref/teref.ont.human.fa

  #IF annotating existing reference, else NULL
  starting_ref: /users/mkelsey/data/ref/pipeline_annotations/hs1/RTE/aref/A.REF.fa

  starting_ref_repeatmasker: /users/mkelsey/data/ref/pipeline_annotations/hs1/RTE/aref/A.REF_repeatmasker/A.REF_repeatmasker_raw.gtf

  ref: aref/A.REF.fa
  ref_index: aref/A.REF.fa.fai
  #use ucsc naming convention, e.g. chr1, chr2, ...
  ref_refseq_gtf: /oscar/data/jsedivy/mkelsey/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.gtf
  ref_refseq_bed: /oscar/data/jsedivy/mkelsey/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.bed
  ref_refseq_gff3: /oscar/data/jsedivy/mkelsey/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.gff
  ref_cytobands: /users/mkelsey/data/ref/genomes/hs1/annotations7/chm13v2.0_cytobands_allchrs.bed
  ref_ccres: /oscar/data/jsedivy/mkelsey/ref/genomes/hs1/annotations3/cCREs/hs1-imr90-cCREsCuratedWithClosestGene.bed
  ref_telomere: /users/mkelsey/data/ref/genomes/hs1/annotations7/chm13v2.0_telomere.bed
  ref_cpgislands: /users/mkelsey/data/ref/genomes/hs1/annotations/hs1_CpG_Island_sorted
  ref_clinvar_bgz: /oscar/data/jsedivy/mkelsey/ref/genomes/hs1/annotations7/chm13v2.0_ClinVar20220313.ncbi-names.vcf.gz
  ref_clinvar_tbi: /oscar/data/jsedivy/mkelsey/ref/genomes/hs1/annotations7/chm13v2.0_ClinVar20220313.ncbi-names.vcf.gz.tbi
  l13fasta: /oscar/data/jsedivy/mkelsey/ref/sequences/l1.3.fa
  repeatmaskerpath: /oscar/data/jsedivy/mkelsey/tools/RepeatMasker/RepeatMasker
  species: human
  #The species name must be a valid NCBI Taxonomy Database species name and be contained in the RepeatMasker repeat database.

ldna:
  ##      ANALYSIS PARAMETERES       ##
  prefix: ldna
  sample_table: "conf/sample_table_ldna.csv"
  default_palette: "ggsci::default_aaas"
  use_aref_basecalls: "yes"
  tldr_input_bams:
  samples:
    - "N2102EP1"

  #order with base comparator as first (dss will have 2 - 1)
  levels:
    - "N2102EP"

  contrasts:
    - ""

  condition_colors:
    N2102EP: "#3C5488FF"

  barcoding: "inactive"
  barcodingKit: ""

  targets:
    - ""

  plasmidFasta: ""
  insertFasta: ""
  backboneFasta: ""
  ecoliFasta: ""
  ##            TOOL PATHS           ##
  dorado: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/bin/dorado"
  ##      ANALYSIS PATHS       ##
  MINIMUM_COVERAGE_FOR_METHYLATION_ANALYSIS: 7
  SEX_CHROMOSOMES_NOT_INCLUDED_IN_ANALYSIS: ""
  reference_annotation_dir: "aref"
  reference: "aref/A.REF.fa"
  annotation: "aref/A.REF_annotations/A.REF_repeatmasker_refseq.complete.gtf"
  refseq_unaltered: "aref/A.REF_annotations/refseq.gff3"
  refseq: "aref/A.REF_annotations/refseq.complete.gtf"
  refseqbgz: "aref/A.REF_annotations/refseq.complete.gff3.gz"
  repeatmasker: "aref/A.REF_annotations/A.REF_repeatmasker.complete.gtf"
  repeatmaskerbgz: "aref/A.REF_annotations/A.REF_repeatmasker.complete.gff3.gz"
  cpg_islands: aref/A.REF_annotations/cpg_islands.bed
  cpgi_shores: aref/A.REF_annotations/cpgi_shores.bed
  cpgi_shelves: aref/A.REF_annotations/cpgi_shelves.bed
  clinvar_bgz: aref/A.REF_annotations/clinvar.vcf.gz
  clinvar_tbi: aref/A.REF_annotations/clinvar.vcf.tbi
  vcfanno_clinvar_toml: conf/clinvar.vcfanno.toml
  intact_l1_anatomy_coordinates: aref/intact_l1_anatomy_coordinates.tsv
  r_annotation_fragmentsjoined: "aref/A.REF_annotations/A.REF_repeatmasker.gtf.rformatted.fragmentsjoined.csv"
  r_repeatmasker_annotation: "aref/A.REF_annotations/A.REF_repeatmasker_annotation.csv"
  l1hsintact: "aref/A.REF_annotations/l1hsintact.bed"
  methylartist_loci_of_interest: "conf/ldna_methylartist_loci_of_interest.bed"
  methylartist_bam_config: "conf/ldna_methylartist_bam_config.txt"
  l13orfs: "/users/mkelsey/data/ref/sequences/l1.3.orfs.txt"
  l13: "/users/mkelsey/data/ref/sequences/l1.3.fa"

  rate: "5khz"
  type: "hac"
  modification_string: "5mCG_5hmCG"

  #note separete modifications with dashes

  basecallingModel:
    4khz:
      hac: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/models/dna_r10.4.1_e8.2_400bps_hac@v4.1.0"
      sup: "/oscar/data/jsedivy/mkelsey/tools/rerio/dorado_models/res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1"
    5khz:
      hac: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/models/dna_r10.4.1_e8.2_400bps_hac@v4.2.0"
  #ensure the clair3model is consistent with the basecalling model
  clair3model: "/oscar/data/jsedivy/mkelsey/tools/remoraModels/r1041_e82_400bps_hac_v420"
  clinvar: ""
  rte_subfamily_extra_modification_analysis:
    - "L1HS_l1_intactness_req_ALL"
    - "L1HS_rte_length_req_ALL"
    - "L1PA2_rte_length_req_ALL"
    - "L1PA3_rte_length_req_ALL"
    - "L1PA4_rte_length_req_ALL"

  rte_subfamily_read_level_analysis:
    - "L1HS_l1_intactness_req_ALL"

lrna:
  prefix: "lrna"
  sample_table: "conf/sample_table_lrna.csv"
  default_palette: "ggsci::default_aaas"
  samples:
    - "pro1"
    - "pro2"
    - "pro3"
    - "sen1"
    - "sen2"
    - "sen3"

  alignmenttypes:
    - "guppy"
    - "dorado"
  counttypes:
    - "relaxed"
    - "stringent"
  levels:
    - "PRO"
    - "SEN"
  levelslegendmap:
    SEN: "SEN"
    PRO: "PRO"
  contrasts:
    - "condition_SEN_vs_PRO"
  contrast_colors:
    condition_SEN_vs_PRO: "red"
  condition_colors:
    SEN: "#F39B7FFF"
    PRO: "#3C5488FF"

  genesets_for_gsea:
    msigdbH: /users/mkelsey/data/ref/genesets/human/msigdb/h.all.v2023.2.Hs.symbols.gmt
    msigdbC2_CPG: /users/mkelsey/data/ref/genesets/human/msigdb/c2.cgp.v2023.2.Hs.symbols.gmt
    msigdbC2_CP: /users/mkelsey/data/ref/genesets/human/msigdb/c2.cp.v2023.2.Hs.symbols.gmt
    msigdbC3_TFT: /users/mkelsey/data/ref/genesets/human/msigdb/c3.tft.v2023.2.Hs.symbols.gmt
    msigdbC5_GO: /users/mkelsey/data/ref/genesets/human/msigdb/c5.go.v2023.2.Hs.symbols.gmt
    msigdbC2_CPG_SENMAYO: /users/mkelsey/data/ref/genesets/human/msigdb/SAUL_SEN_MAYO.v2023.2.Hs.gmt

  genesets_for_heatmaps:
    Senescence: /users/mkelsey/data/ref/genesets/human/mycustom/senescence.txt
    InflammatoryGenes: /users/mkelsey/data/ref/genesets/human/mycustom/inflammatory.txt

  genelistsforplot:
    - "/users/mkelsey/data/ref/genesets/sasp.txt"

  #specify strand for stranded plotting of rnaseq data
  regions_of_interest: "conf/lrna_regions_of_interest.bed"

  paralellize_bioc: 8

  dorado: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/bin/dorado"
  guppy: "/oscar/data/jsedivy/mkelsey/tools/ont-guppy/bin/guppy_basecaller"
  guppy_config: "/oscar/data/jsedivy/mkelsey/tools/ont-guppy/data/rna_r9.4.1_70bps_sup.cfg"

  reference: "aref/A.REF.fa"
  rtes_genes_gtf: "aref/A.REF_annotations/A.REF_repeatmasker_refseq.complete.gtf"

  basecallingModel: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/models/rna002_70bps_hac@v3"
  junctionbed: "/users/mkelsey/data/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.bed"
  referencetranscriptome: "/oscar/data/jsedivy/mkelsey/ref/transcriptome/GRCh38_latest_rna_andRCS.fna"

  ## new additions
  annotation_genes: "aref/A.REF_annotations/refseq.gtf"
  annotation_genes_bed12: "/oscar/data/jsedivy/mkelsey/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.bed"
  annotation_genesandrtes: "aref/A.REF_annotations/A.REF_repeatmasker_refseq.complete.gtf"
  annotation_rtes: "aref/A.REF_annotations/A.REF_repeatmasker.gff2"
  annotation_genesandrtes_fasta: "aref/A.REF_annotations/A.REF_repeatmasker_refseq.complete.fa"

  r_annotation_fragmentsjoined: "aref/A.REF_annotations/A.REF_repeatmasker.gtf.rformatted.fragmentsjoined.csv"
  r_repeatmasker_annotation: "aref/A.REF_annotations/A.REF_repeatmasker_annotation.csv"
  txdb: "aref/A.REF_annotations/A.REF_repeatmasker_refseq.complete.sqlite"
  cytobands: "aref/A.REF_annotations/cytobands.bed"
  mycoplasma: "/users/mkelsey/data/ref/genomes/mycoplasma/mycoplasma.fa"

srna:
  prefix: "srna"
  sample_table: "conf/sample_table_srna.csv"
  peptable: "conf/peptable_srna.csv"
  default_palette: "ggsci::default_aaas"
  samples:
    - "RS_0w_low_O2_1"
    - "RS_0w_low_O2_2"
    - "RS_0w_low_O2_3"
    - "RS_4w_low_O2_1"
    - "RS_4w_low_O2_2"
    - "RS_4w_low_O2_3"
    - "RS_8w_low_O2_1"
    - "RS_8w_low_O2_2"
    - "RS_8w_low_O2_3"
    - "RS_12w_low_O2_1"
    - "RS_12w_low_O2_2"
    - "RS_12w_low_O2_3"
    - "PRO_normoxic_1"
    - "PRO_normoxic_2"
    - "PRO_normoxic_3"
    - "DDIS_8w_low_O2_1"
    - "DDIS_8w_low_O2_2"
    - "DDIS_8w_low_O2_3"
    - "PRO_low_O2_1"
    - "PRO_low_O2_2"
    - "PRO_low_O2_3"

  paralellize_bioc: 8
  counttypes:
    - "featurecounts_genes"
  tecounttypes:
    - "telescope_multi"

  #paired end (PE), or single end (SE)
  library_type: PE
  #order matters for levels! first is the base comparator
  levels:
    - "PRO_low_O2"
    - "RS_0w_low_O2"
    - "RS_4w_low_O2"
    - "RS_8w_low_O2"
    - "RS_12w_low_O2"
    - "PRO_normoxic"
    - "DDIS_8w_low_O2"

  #mappings
  levelslegendmap:
    PRO_low_O2: "PRO_low_O2"
    RS_0w_low_O2: "RS_0w_low_O2"
    RS_4w_low_O2: "RS_4w_low_O2"
    RS_8w_low_O2: "RS_8w_low_O2"
    RS_12w_low_O2: "RS_12w_low_O2"
    PRO_normoxic: "PRO_normoxic"
    DDIS_8w_low_O2: "DDIS_8w_low_O2"

  #analysis settings
  contrasts:
    - "condition_RS_0w_low_O2_vs_PRO_low_O2"
    - "condition_RS_4w_low_O2_vs_PRO_low_O2"
    - "condition_RS_8w_low_O2_vs_PRO_low_O2"
    - "condition_RS_12w_low_O2_vs_PRO_low_O2"
    - "condition_PRO_normoxic_vs_PRO_low_O2"
    - "condition_DDIS_8w_low_O2_vs_PRO_low_O2"

  contrast_colors:
    condition_RS_0w_low_O2_vs_PRO_low_O2: yellow
    condition_RS_4w_low_O2_vs_PRO_low_O2: orange
    condition_RS_8w_low_O2_vs_PRO_low_O2: red
    condition_RS_12w_low_O2_vs_PRO_low_O2: purple
    condition_PRO_normoxic_vs_PRO_low_O2: blue
    condition_DDIS_8w_low_O2_vs_PRO_low_O2: magenta

  condition_colors:
    PRO_low_O2: grey
    RS_0w_low_O2: yellow
    RS_4w_low_O2: orange
    RS_8w_low_O2: red
    RS_12w_low_O2: purple
    PRO_normoxic: blue
    DDIS_8w_low_O2: magenta

  genesets_for_gsea:
    msigdbH: /users/mkelsey/data/ref/genesets/human/msigdb/h.all.v2023.2.Hs.symbols.gmt
    msigdbC2_CPG: /users/mkelsey/data/ref/genesets/human/msigdb/c2.cgp.v2023.2.Hs.symbols.gmt
    msigdbC2_CP: /users/mkelsey/data/ref/genesets/human/msigdb/c2.cp.v2023.2.Hs.symbols.gmt
    msigdbC3_TFT: /users/mkelsey/data/ref/genesets/human/msigdb/c3.tft.v2023.2.Hs.symbols.gmt
    msigdbC5_GO: /users/mkelsey/data/ref/genesets/human/msigdb/c5.go.v2023.2.Hs.symbols.gmt
    msigdbC2_CPG_SENMAYO: /users/mkelsey/data/ref/genesets/human/msigdb/SAUL_SEN_MAYO.v2023.2.Hs.gmt

  genesets_for_heatmaps:
    Senescence: /users/mkelsey/data/ref/genesets/human/mycustom/senescence.txt
    InflammatoryGenes: /users/mkelsey/data/ref/genesets/human/mycustom/inflammatory.txt

  annotation_genes: "aref/A.REF_annotations/refseq.gtf"
  annotation_genes_bed12: "aref/A.REF_annotations/refseq.complete.bed"
  annotation_genesandrtes: "A.REF_repeatmasker_refseq.complete.gtf"
  annotation_rtes: "aref/A.REF_annotations/A.REF_repeatmasker.gff2"

  r_annotation_fragmentsjoined: "aref/A.REF_annotations/A.REF_repeatmasker.gtf.rformatted.fragmentsjoined.csv"
  r_repeatmasker_annotation: "aref/A.REF_annotations/A.REF_repeatmasker_annotation.csv"

  #genomes
  reference: "aref/A.REF.fa"
  starindex: "aref/A.REF_indeces/star_index"

  # referencesize: "/users/mkelsey/data/ref/genomes/hs1/hs1.chrom.sizes.txt"
  #indeces

integrated:
  regions_of_interest: "conf/integrated_regions_of_interest.bed"
