#META PIPELINE SETTINGS
pipelines_to_deploy:
  # - srna
  - gref
  - aref
  # - ldna
  # - lrna

#PIPELINE SETTINGS - Ignore settings for pipelines not being deployed
gref:
  prefix: gref
  starting_ref: /oscar/data/jsedivy/mkelsey/ref/genomes/hs1/hs1.sorted.fa
  tldr_input_bam: bampath

aref:
  prefix: aref
  ref: /users/mkelsey/data/ref/generate/lf1/GetRef/updated_ref/updated_ref.fa
  ref_index: /users/mkelsey/data/ref/generate/lf1/GetRef/updated_ref/updated_ref.fa.fai
  ref_refseq: /oscar/data/jsedivy/mkelsey/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.gtf
  ref_refseq_gff3: /oscar/data/jsedivy/mkelsey/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.gff
  ref_cytobands: /users/mkelsey/data/ref/genomes/hs1/annotations7/chm13v2.0_cytobands_allchrs.bed
  ref_ccres: /oscar/data/jsedivy/mkelsey/ref/genomes/hs1/annotations3/cCREs/hs1-imr90-cCREsCuratedWithClosestGene.bed
  ref_telomere: /users/mkelsey/data/ref/genomes/hs1/annotations7/chm13v2.0_telomere.bed
  ref_cpgislands: /users/mkelsey/data/ref/genomes/hs1/annotations/hs1_CpG_Island_sorted
  l13fasta: /oscar/data/jsedivy/mkelsey/ref/sequences/l1.3.fa
  repeatmaskerpath: /oscar/data/jsedivy/mkelsey/tools/RepeatMasker/RepeatMasker
  species: human
  #The species name must be a valid NCBI Taxonomy Database species name and be contained in the RepeatMasker repeat database.

ldna:
  ##      ANALYSIS PARAMETERES       ##
  prefix: ldna
  samples:
    - "NTERA1"

  #order with base comparator as first (dss will have 2 - 1)
  conditions:
    - "NTERA"

  barcoding: "inactive"
  barcodingKit: ""

  DNA: "active"
  RNA: "inactive"

  targets:
    - ""

  plasmidFasta: ""
  insertFasta: ""
  backboneFasta: ""
  ecoliFasta: ""
  ##            TOOL PATHS           ##
  dorado: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/bin/dorado"
  ##      ANALYSIS PATHS       ##

  reference_annotation_dir: "/users/mkelsey/data/ref/generate/hs1/AnnotateReference"
  reference: "/users/mkelsey/data/ref/generate/hs1/AnnotateReference/ref.fa"
  annotation: "/users/mkelsey/data/ref/generate/hs1/AnnotateReference/annotations/repeatmasker_refseq.complete.gtf"
  refseq: "/users/mkelsey/data/ref/generate/hs1/AnnotateReference/annotations/refseq.complete.gtf"
  refseqbgz: "/users/mkelsey/data/ref/generate/hs1/AnnotateReference/annotations/refseq.complete.gff3.gz"
  repeatmasker: "/users/mkelsey/data/ref/generate/hs1/AnnotateReference/annotations/repeatmasker.complete.gtf"
  repeatmaskerbgz: "/users/mkelsey/data/ref/generate/hs1/AnnotateReference/annotations/repeatmasker.complete.gff3.gz"
  cpg_islands: /users/mkelsey/data/ref/generate/hs1/AnnotateReference/annotations/cpg_islands.bed
  cpgi_shores: /users/mkelsey/data/ref/generate/hs1/AnnotateReference/annotations/cpgi_shores.bed
  cpgi_shelves: /users/mkelsey/data/ref/generate/hs1/AnnotateReference/annotations/cpgi_shelves.bed
  intact_l1_anatomy_coordinates: /users/mkelsey/data/ref/generate/hs1/AnnotateReference/intact_l1_anatomy_coordinates.tsv
  r_annotation_fragmentsjoined: "/users/mkelsey/data/ref/generate/hs1/AnnotateReference/annotations/repeatmasker.gtf.rformatted.fragmentsjoined.csv"
  r_repeatmasker_annotation: "/users/mkelsey/data/ref/generate/hs1/AnnotateReference/annotations/repeatmasker_annotation.csv"
  l1hsintact: "/users/mkelsey/data/ref/generate/hs1/AnnotateReference/annotations/l1hsintact.bed"
  methylartist_loci_of_interest: "conf/ldna_methylartist_loci_of_interest.bed"
  methylartist_bam_config: "conf/ldna_methylartist_bam_config.txt"
  l13orfs: "/users/mkelsey/data/ref/sequences/l1.3.orfs.txt"
  l13: "/users/mkelsey/data/ref/sequences/l1.3.fa"

  rate: "5khz"
  type: "hac"
  modification_string: "6mA-5mC_5hmC"
  #note separete modifications with dashes

  basecallingModel:
    4khz:
      hac: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/models/dna_r10.4.1_e8.2_400bps_hac@v4.1.0"
      sup: "/oscar/data/jsedivy/mkelsey/tools/rerio/dorado_models/res_dna_r10.4.1_e8.2_400bps_sup@v4.0.1"
    5khz:
      hac: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/models/dna_r10.4.1_e8.2_400bps_hac@v4.2.0"

  rte_subfamily_extra_modification_analysis:
    - "L1HS_l1_intactness_req_ALL"
    - "L1HS_rte_length_req_ALL"
    - "L1PA2_rte_length_req_ALL"
    - "L1PA3_rte_length_req_ALL"
    - "L1PA4_rte_length_req_ALL"

  rte_subfamily_read_level_analysis:
    - "L1HS_l1_intactness_req_ALL"

lrna:
  prefix: "lrna"
  samples:
    - "pro1"
    - "pro2"
    - "pro3"
    - "sen1"
    - "sen2"
    - "sen3"

  alignmenttypes:
    - "guppy"
    - "dorado"
  counttypes:
    - "relaxed"
    - "stringent"
  levels:
    - "PRO"
    - "SEN"
  levelslegendmap:
    SEN: "SEN"
    PRO: "PRO"
  contrasts:
    - "condition_SEN_vs_PRO"
  contrast_colors:
    condition_SEN_vs_PRO: "red"
  condition_colors:
    SEN: "#F39B7FFF"
    PRO: "#3C5488FF"

  genesets_for_gsea:
    msigdbH: /users/mkelsey/data/ref/genesets/human/msigdb/h.all.v2023.2.Hs.symbols.gmt
    msigdbC2_CPG: /users/mkelsey/data/ref/genesets/human/msigdb/c2.cgp.v2023.2.Hs.symbols.gmt
    msigdbC2_CP: /users/mkelsey/data/ref/genesets/human/msigdb/c2.cp.v2023.2.Hs.symbols.gmt
    msigdbC3_TFT: /users/mkelsey/data/ref/genesets/human/msigdb/c3.tft.v2023.2.Hs.symbols.gmt
    msigdbC5_GO: /users/mkelsey/data/ref/genesets/human/msigdb/c5.go.v2023.2.Hs.symbols.gmt
    msigdbC2_CPG_SENMAYO: /users/mkelsey/data/ref/genesets/human/msigdb/SAUL_SEN_MAYO.v2023.2.Hs.gmt

  genesets_for_heatmaps:
    Senescence: /users/mkelsey/data/ref/genesets/human/mycustom/senescence.txt
    InflammatoryGenes: /users/mkelsey/data/ref/genesets/human/mycustom/inflammatory.txt

  genelistsforplot:
    - "/users/mkelsey/data/ref/genesets/sasp.txt"

  #specify strand for stranded plotting of rnaseq data
  regions_of_interest: "conf/lrna_regions_of_interest.bed"

  paralellize_bioc: 8

  dorado: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/bin/dorado"
  guppy: "/oscar/data/jsedivy/mkelsey/tools/ont-guppy/bin/guppy_basecaller"
  guppy_config: "/oscar/data/jsedivy/mkelsey/tools/ont-guppy/data/rna_r9.4.1_70bps_sup.cfg"

  sample_table: "conf/sample_table_lrna.csv"
  reference: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/ref.fa"
  rtes_genes_gtf: "/oscar/data/jsedivy/mkelsey/ref/genomes/hs1/annotations4/hs1.repMask.refseq.nonref.sorted.gtf"

  basecallingModel: "/users/mkelsey/data/tools/dorado-0.5.1-linux-x64/models/rna002_70bps_hac@v3"
  junctionbed: "/users/mkelsey/data/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.bed"
  referencetranscriptome: "/oscar/data/jsedivy/mkelsey/ref/transcriptome/GRCh38_latest_rna_andRCS.fna"

  ## new additions
  annotation_genes: "/oscar/data/jsedivy/mkelsey/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.gtf"
  annotation_genes_bed12: "/oscar/data/jsedivy/mkelsey/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.bed"
  annotation_genesandrtes: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/repeatmasker_refseq.complete.gtf"
  annotation_rtes: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/repeatmasker.gff2"
  annotation_genesandrtes_fasta: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/repeatmasker_refseq.complete.fa"

  r_annotation_fragmentsjoined: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/repeatmasker.gtf.rformatted.fragmentsjoined.csv"
  r_repeatmasker_annotation: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/repeatmasker_annotation.csv"
  txdb: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/repeatmasker_refseq.complete.sqlite"
  cytobands: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/cytobands.bed"
  mycoplasma: "/users/mkelsey/data/ref/genomes/mycoplasma/mycoplasma.fa"

srna:
  prefix: "srna"
  sample_table: "conf/sample_table_srna.csv"
  peptable: "conf/peptable_srna.csv"

  samples:
    - "PRO1"
    - "PRO2"
    - "PRO3"
    - "SEN1"
    - "SEN2"
    - "SEN3"

  paralellize_bioc: 8
  counttypes:
    - "featurecounts_genes"
  tecounttypes:
    - "telescope_multi"

  #paired end (PE), or single end (SE)
  library_type: PE
  #order matters for levels! first is the base comparator
  levels:
    - "PRO"
    - "SEN"

  #mappings
  levelslegendmap:
    SEN: "SEN"
    PRO: "PRO"

  #analysis settings
  contrasts:
    - "condition_SEN_vs_PRO"

  contrast_colors:
    condition_SEN_vs_PRO: "red"

  condition_colors:
    SEN: "red"
    PRO: "blue"

  genesets_for_gsea:
    msigdbH: /users/mkelsey/data/ref/genesets/human/msigdb/h.all.v2023.2.Hs.symbols.gmt
    msigdbC2_CPG: /users/mkelsey/data/ref/genesets/human/msigdb/c2.cgp.v2023.2.Hs.symbols.gmt
    msigdbC2_CP: /users/mkelsey/data/ref/genesets/human/msigdb/c2.cp.v2023.2.Hs.symbols.gmt
    msigdbC3_TFT: /users/mkelsey/data/ref/genesets/human/msigdb/c3.tft.v2023.2.Hs.symbols.gmt
    msigdbC5_GO: /users/mkelsey/data/ref/genesets/human/msigdb/c5.go.v2023.2.Hs.symbols.gmt
    msigdbC2_CPG_SENMAYO: /users/mkelsey/data/ref/genesets/human/msigdb/SAUL_SEN_MAYO.v2023.2.Hs.gmt

  genesets_for_heatmaps:
    Senescence: /users/mkelsey/data/ref/genesets/human/mycustom/senescence.txt
    InflammatoryGenes: /users/mkelsey/data/ref/genesets/human/mycustom/inflammatory.txt

  annotation_genes: "/oscar/data/jsedivy/mkelsey/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.gtf"
  annotation_genes_bed12: "/oscar/data/jsedivy/mkelsey/ref/genomes/hs1/refseq_2023_10/GCF_009914755.1_T2T-CHM13v2.0_genomic.ucscnames.bed"
  annotation_genesandrtes: "/oscar/data/jsedivy/mkelsey/ref/genomes/hs1/annotations4/hs1.repMask.refseq.sorted.gtf"
  annotation_rtes: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/repeatmasker.gff2"

  r_annotation_fragmentsjoined: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/repeatmasker.gtf.rformatted.fragmentsjoined.csv"
  r_repeatmasker_annotation: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/annotations/repeatmasker_annotation.csv"

  #genomes
  reference: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/ref.fa"
  starindex: "/users/mkelsey/data/ref/generate/lf1/AnnotateReference/ref_indeces/star_index"

  # referencesize: "/users/mkelsey/data/ref/genomes/hs1/hs1.chrom.sizes.txt"
  #indeces

  telocalmapping: "/users/mkelsey/data/ref/genomes/hs1/TElocal/T2T_CHM13_v2_rmsk_TE.gtf.locInd.locations.annotated.intactnessAnn"
  bowtie2hs1index: "/users/mkelsey/data/ref/genomes/hs1/hs1.sorted_bowtie2/hs1"

  genelistsforplot:
    - "/users/mkelsey/data/ref/genesets/sasp.txt"
  #annotations
  ideogram: "/users/mkelsey/data/ref/genomes/hs1/annotations2/Ideogram.bed"
  ideogram2: "/users/mkelsey/data/ref/genomes/hs1/annotations2/ideogramWithStain.bed"
  repeats: "/users/mkelsey/data/ref/genomes/hs1/annotations/hs1_RepeatMasker.sorted"
  repeatsbed: "/users/mkelsey/data/ref/genomes/hs1/annotations/repeatmasker.bed"
  repeats2: "/users/mkelsey/data/ref/genomes/hs1/annotations2/repeatMasker.gtf"
  repeats2gz: "/users/mkelsey/data/ref/genomes/hs1/annotations2/repeatMasker.copy.gtf.gz"

  repeatsannotated: "/users/mkelsey/data/ref/genomes/hs1/annotations2/repeatMaskerAnnotated.bed"
  l1hs6kb: "/users/mkelsey/data/ref/genomes/hs1/annotations/L1HS6kb"
  aluY: "/users/mkelsey/data/ref/genomes/hs1/annotations/aluY"
  HERVK: "/users/mkelsey/data/ref/genomes/hs1/annotations/HERVK"
  intactl1s: "/users/mkelsey/data/ref/genomes/hs1/annotations2/subsets/l1hsintact.bed"
  l1hs6kbintact: "/users/mkelsey/data/ref/genomes/hs1/annotations/L1HS6kbintact"
  l1hs6kbintactbed: "/users/mkelsey/data/ref/genomes/hs1/annotations/L1HS6kbintact.bed5"
  SenMayoHuman: "/users/mkelsey/data/ref/genesets/SenMayoGeneSetHuman.txt"
  l1hsorf2intact:
    "/gpfs/data/jsedivy/mkelsey/ref/genomes/hs1/annotations/blast_repeatmasker/l1/orf2/L1_ORF2intact.bed"

    #these are for the ideogram
  namedcolorlist:
    L1UP: "8c00ff"
    AluUP: "ff9d00"
    ERVKUP: "ff7be2"
    L1HSUP: "8c00ff"
    AluYUP: "ff9d00"
    HERVK-intUP: "ff7be2"
    L1DOWN: "00ff62"
    AluDOWN: "0be7e4"
    ERVKDOWN: "8c00ff"
    L1HSDOWN: "00ff62"
    AluYDOWN: "0be7e4"
    HERVK-intDOWN: "8c00ff"

  namedmarkerlist:
    L1: "circle"
    Alu: "box"
    ERVK: "triange"
    L1HS: "circle"
    AluY: "box"
    HERVK-int: "triangle"

  activeelementminlength:
    L1HS: 5999
    AluY: 280
    HERVK-int: 7000
    L1PA2: 5000
    L1PA3: 5000
    L1PA4: 5000
    L1PA5: 5000
    L1PA6-9: 5000

  lengthreq:
    "L1": 0
    "Alu": 0
    "ERVK": 0
    "L1HS": 5999
    "AluY": 280
    "HERVK-int": 7000
    "L1PA2": 5000
    "L1PA3": 5000
    "L1PA4": 5000
    "L1PA5": 5000
    "L1PA6-9": 5000

  rtestoplot:
    - "L1HS"
    - "AluY"
    - "HERVK-int"

  repeatanalysis:
    "Family":
      "L1": "L1:LINE"
      "Alu": "Alu:SINE"
      "ERVK": "ERVK:LTR"
    "ActiveFamily":
      "L1HS": "L1HS"
      "AluY": "AluY"
      "HERVK-int": "HERVK(.)*int"
    "Subfamily":
      "L1HS": "L1HS"
      "AluY": "AluY"
      "HERVK-int": "HERVK(.)*int"
      "L1PA2": "L1PA2"
      "L1PA3": "L1PA3"
      "L1PA4": "L1PA4"
      "L1PA5": "L1PA5"
      "L1PA6-9": "L1PA[6789]{1}"

  genedensity:
    L1HS: "/users/mkelsey/data/ref/genomes/hs1/annotations/hs1.L1HS.density.bed4"
    AluY: "/users/mkelsey/data/ref/genomes/hs1/annotations/hs1.HERVK.density.bed4"
    HERVK-int: "/users/mkelsey/data/ref/genomes/hs1/annotations/hs1.AluY.density.bed4"

  karyotype: "/users/mkelsey/data/ref/genomes/hs1/karyotype.tsv"

  L1HSconsensus: "/users/mkelsey/data/ref/sequences/L1HSconsensus.fa"
  AluYconsensus: "/users/mkelsey/data/ref/sequences/AluYconsensus.fa"
  HERVK-intconsensus: "/users/mkelsey/data/ref/sequences/HERVK-intconsensus.fa"
  L1HSoutgroup: "/users/mkelsey/data/ref/sequences/L1HSconsensus.fa"
  AluYoutgroup: "/users/mkelsey/data/ref/sequences/AluJbconsensus.fa"
  HERVK-intoutgroup: "/users/mkelsey/data/ref/sequences/HERVL-intconsensus.fa"
